name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: 'Dockerfile'
            tags: [ "zyuzka/elasticsearch:5.6" ]
            es-version: '5.6.16'
            platforms: [ 'linux/amd64', 'linux/arm64' ]

          - image: 'Dockerfile'
            tags: [ "zyuzka/elasticsearch:6.8" ]
            es-version: '6.8.4'
            platforms: [ 'linux/amd64', 'linux/arm64' ]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          build-args: |
            ELASTICSEARCH_VERSION=${{ matrix.es-version }}
          platforms: ${{ join(matrix.platforms) }}
