name: Kibana-CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: 'kibana/5.6.16.Dockerfile'
            tags: [ "zyuzka/kibana:5.6" ]
            platforms: [ 'linux/amd64', 'linux/arm64' ]

          - image: 'kibana/6.8.4.Dockerfile'
            tags: [ "zyuzka/kibana:6.8" ]
            platforms: [ 'linux/amd64', 'linux/arm64' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./kibana
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          platforms: ${{ join(matrix.platforms) }}
